"""initial schema

Revision ID: 3eb0672162e8
Revises: 
Create Date: 2026-09-18 06:13:23.267326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3eb0672162e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_record_type', sa.String(length=50), nullable=True),
    sa.Column('related_record_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('account_identifier_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('account_identifier_last4', sa.String(length=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('BANK','MOBILE_MONEY','CASH','SAVINGS','INVESTMENT','OTHER')", name='ck_bank_account_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_account_user_active', 'bank_accounts', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_table('distribution_rules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_rules_user_id'), 'distribution_rules', ['user_id'], unique=False)
    op.create_index('ux_distribution_rules_user_default', 'distribution_rules', ['user_id'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('savings_distribution_rules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_distribution_rules_user_id'), 'savings_distribution_rules', ['user_id'], unique=False)
    op.create_index('ux_savings_dist_rule_user_default', 'savings_distribution_rules', ['user_id'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.create_table('distribution_categories',
    sa.Column('distribution_rule_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('contributes_to_automatic_savings', sa.Boolean(), nullable=False),
    sa.Column('is_unallocated_bucket', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distribution_rule_id'], ['distribution_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distribution_rule_id', 'name', name='ux_distribution_category_rule_name')
    )
    op.create_index(op.f('ix_distribution_categories_distribution_rule_id'), 'distribution_categories', ['distribution_rule_id'], unique=False)
    op.create_index('ux_distribution_category_unallocated_bucket', 'distribution_categories', ['distribution_rule_id'], unique=True, postgresql_where=sa.text('is_unallocated_bucket = true'))
    op.create_table('financial_periods',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('distribution_rule_id', sa.UUID(), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('reopened_count', sa.SmallInteger(), nullable=False),
    sa.Column('last_reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED')", name='ck_financial_period_status'),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='ck_financial_period_month_range'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['distribution_rule_id'], ['distribution_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='ux_financial_period_user_year_month')
    )
    op.create_index('ix_financial_period_user_status', 'financial_periods', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_financial_periods_user_id'), 'financial_periods', ['user_id'], unique=False)
    op.create_table('savings_distribution_rule_items',
    sa.Column('savings_distribution_rule_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('destination_label', sa.String(length=150), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bank_account_id IS NOT NULL OR destination_label IS NOT NULL', name='ck_savings_dist_rule_item_destination'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['savings_distribution_rule_id'], ['savings_distribution_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_distribution_rule_items_savings_distribution_rule_id'), 'savings_distribution_rule_items', ['savings_distribution_rule_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=15), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('source_reference', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_record_type', sa.String(length=30), nullable=True),
    sa.Column('related_record_id', sa.UUID(), nullable=True),
    sa.Column('transfer_pair_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('DEPOSIT','WITHDRAWAL','TRANSFER_IN','TRANSFER_OUT','ADJUSTMENT')", name='ck_bank_txn_type'),
    sa.CheckConstraint('amount > 0', name='ck_bank_txn_amount_positive'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['financial_period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_bank_account_id'), 'bank_transactions', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_financial_period_id'), 'bank_transactions', ['financial_period_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_user_id'), 'bank_transactions', ['user_id'], unique=False)
    op.create_index('ix_bank_txn_account_date', 'bank_transactions', ['bank_account_id', 'transaction_date'], unique=False)
    op.create_index('ix_bank_txn_period', 'bank_transactions', ['financial_period_id'], unique=False)
    op.create_table('monthly_financial_summaries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('total_salary_income', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_allowances', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_other_income', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_monthly_income', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_planned_savings', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('automatic_savings', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('manual_savings', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('final_savings', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_bank_deposits', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('undistributed_savings', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('triggered_by', sa.String(length=10), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("triggered_by IN ('CLOSE','REOPEN_RECALC','MANUAL_REFRESH')", name='ck_monthly_summary_triggered_by'),
    sa.ForeignKeyConstraint(['financial_period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_period_id', 'version', name='ux_monthly_summary_period_version')
    )
    op.create_index(op.f('ix_monthly_financial_summaries_financial_period_id'), 'monthly_financial_summaries', ['financial_period_id'], unique=False)
    op.create_index(op.f('ix_monthly_financial_summaries_user_id'), 'monthly_financial_summaries', ['user_id'], unique=False)
    op.create_index('ux_monthly_summary_current', 'monthly_financial_summaries', ['financial_period_id'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('recurring_templates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=True),
    sa.Column('start_period_id', sa.UUID(), nullable=True),
    sa.Column('end_period_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency = 'MONTHLY'", name='ck_recurring_template_frequency_v1'),
    sa.CheckConstraint("record_type IN ('SALARY','ALLOWANCE','INCOME','EXPENSE')", name='ck_recurring_template_record_type'),
    sa.CheckConstraint('amount >= 0', name='ck_recurring_template_amount_nonneg'),
    sa.ForeignKeyConstraint(['end_period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['start_period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurring_template_user_active', 'recurring_templates', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_recurring_templates_user_id'), 'recurring_templates', ['user_id'], unique=False)
    op.create_table('savings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('automatic_savings_computed', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('manual_savings_total', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('final_savings_total', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('distributed_total', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('undistributed_total', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('undistributed_total >= 0', name='ck_savings_undistributed_nonneg'),
    sa.ForeignKeyConstraint(['financial_period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_period_id', name='ux_savings_period')
    )
    op.create_index(op.f('ix_savings_user_id'), 'savings', ['user_id'], unique=False)
    op.create_table('allowances',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_template_id', sa.UUID(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_allowance_amount_nonneg'),
    sa.ForeignKeyConstraint(['financial_period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['recurring_template_id'], ['recurring_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_allowance_user_period', 'allowances', ['user_id', 'financial_period_id'], unique=False)
    op.create_index(op.f('ix_allowances_financial_period_id'), 'allowances', ['financial_period_id'], unique=False)
    op.create_index(op.f('ix_allowances_user_id'), 'allowances', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('distribution_category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('expense_category', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_template_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("expense_category IN ('RENT','FOOD','TRANSPORTATION','ELECTRICITY','WATER','INTERNET','PHONE','EDUCATION','HEALTHCARE','FAMILY_SUPPORT','ENTERTAINMENT','SHOPPING','DEBT_REPAYMENT','OTHER')", name='ck_expense_category'),
    sa.CheckConstraint("payment_method IN ('CASH','BANK_TRANSFER','CARD','MOBILE_MONEY','OTHER')", name='ck_expense_payment_method'),
    sa.CheckConstraint('amount > 0', name='ck_expense_amount_positive'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['distribution_category_id'], ['distribution_categories.id'], ),
    sa.ForeignKeyConstraint(['financial_period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['recurring_template_id'], ['recurring_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expense_distribution_category', 'expenses', ['distribution_category_id'], unique=False)
    op.create_index('ix_expense_user_category', 'expenses', ['user_id', 'expense_category'], unique=False)
    op.create_index('ix_expense_user_period', 'expenses', ['user_id', 'financial_period_id'], unique=False)
    op.create_index(op.f('ix_expenses_financial_period_id'), 'expenses', ['financial_period_id'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('income',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('income_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_template_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("income_type IN ('IN_COUNTRY_PAYMENT','PER_DIEM','FREELANCE','BUSINESS','INVESTMENT','OTHER')", name='ck_income_type'),
    sa.CheckConstraint('amount >= 0', name='ck_income_amount_nonneg'),
    sa.ForeignKeyConstraint(['financial_period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['recurring_template_id'], ['recurring_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_financial_period_id'), 'income', ['financial_period_id'], unique=False)
    op.create_index('ix_income_type', 'income', ['income_type'], unique=False)
    op.create_index(op.f('ix_income_user_id'), 'income', ['user_id'], unique=False)
    op.create_index('ix_income_user_period', 'income', ['user_id', 'financial_period_id'], unique=False)
    op.create_table('salaries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recurring_template_id', sa.UUID(), nullable=True),
    sa.Column('is_recurring_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('EXPECTED','RECEIVED')", name='ck_salary_status'),
    sa.CheckConstraint('net_amount >= 0', name='ck_salary_net_amount_nonneg'),
    sa.ForeignKeyConstraint(['financial_period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['recurring_template_id'], ['recurring_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'financial_period_id', name='ux_salary_user_period')
    )
    op.create_index(op.f('ix_salaries_financial_period_id'), 'salaries', ['financial_period_id'], unique=False)
    op.create_index(op.f('ix_salaries_user_id'), 'salaries', ['user_id'], unique=False)
    op.create_table('savings_allocations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('savings_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('destination_label', sa.String(length=150), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('allocation_method', sa.String(length=10), nullable=False),
    sa.Column('bank_transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("allocation_method IN ('AUTO','MANUAL')", name='ck_savings_allocation_method'),
    sa.CheckConstraint('amount > 0', name='ck_savings_allocation_amount_positive'),
    sa.CheckConstraint('bank_account_id IS NOT NULL OR destination_label IS NOT NULL', name='ck_savings_allocation_destination'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['savings_id'], ['savings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_allocations_savings_id'), 'savings_allocations', ['savings_id'], unique=False)
    op.create_index(op.f('ix_savings_allocations_user_id'), 'savings_allocations', ['user_id'], unique=False)
    op.create_table('savings_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('financial_period_id', sa.UUID(), nullable=False),
    sa.Column('savings_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_savings_item_amount_positive'),
    sa.ForeignKeyConstraint(['financial_period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['savings_id'], ['savings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_items_financial_period_id'), 'savings_items', ['financial_period_id'], unique=False)
    op.create_index(op.f('ix_savings_items_user_id'), 'savings_items', ['user_id'], unique=False)
    op.create_table('attachments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('file_size_bytes > 0', name='ck_attachment_file_size_positive'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_expense_id'), 'attachments', ['expense_id'], unique=False)
    op.create_index(op.f('ix_attachments_user_id'), 'attachments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_user_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_expense_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_savings_items_user_id'), table_name='savings_items')
    op.drop_index(op.f('ix_savings_items_financial_period_id'), table_name='savings_items')
    op.drop_table('savings_items')
    op.drop_index(op.f('ix_savings_allocations_user_id'), table_name='savings_allocations')
    op.drop_index(op.f('ix_savings_allocations_savings_id'), table_name='savings_allocations')
    op.drop_table('savings_allocations')
    op.drop_index(op.f('ix_salaries_user_id'), table_name='salaries')
    op.drop_index(op.f('ix_salaries_financial_period_id'), table_name='salaries')
    op.drop_table('salaries')
    op.drop_index('ix_income_user_period', table_name='income')
    op.drop_index(op.f('ix_income_user_id'), table_name='income')
    op.drop_index('ix_income_type', table_name='income')
    op.drop_index(op.f('ix_income_financial_period_id'), table_name='income')
    op.drop_table('income')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_financial_period_id'), table_name='expenses')
    op.drop_index('ix_expense_user_period', table_name='expenses')
    op.drop_index('ix_expense_user_category', table_name='expenses')
    op.drop_index('ix_expense_distribution_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_allowances_user_id'), table_name='allowances')
    op.drop_index(op.f('ix_allowances_financial_period_id'), table_name='allowances')
    op.drop_index('ix_allowance_user_period', table_name='allowances')
    op.drop_table('allowances')
    op.drop_index(op.f('ix_savings_user_id'), table_name='savings')
    op.drop_table('savings')
    op.drop_index(op.f('ix_recurring_templates_user_id'), table_name='recurring_templates')
    op.drop_index('ix_recurring_template_user_active', table_name='recurring_templates')
    op.drop_table('recurring_templates')
    op.drop_index('ux_monthly_summary_current', table_name='monthly_financial_summaries', postgresql_where=sa.text('is_current = true'))
    op.drop_index(op.f('ix_monthly_financial_summaries_user_id'), table_name='monthly_financial_summaries')
    op.drop_index(op.f('ix_monthly_financial_summaries_financial_period_id'), table_name='monthly_financial_summaries')
    op.drop_table('monthly_financial_summaries')
    op.drop_index('ix_bank_txn_period', table_name='bank_transactions')
    op.drop_index('ix_bank_txn_account_date', table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_user_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_financial_period_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_savings_distribution_rule_items_savings_distribution_rule_id'), table_name='savings_distribution_rule_items')
    op.drop_table('savings_distribution_rule_items')
    op.drop_index(op.f('ix_financial_periods_user_id'), table_name='financial_periods')
    op.drop_index('ix_financial_period_user_status', table_name='financial_periods')
    op.drop_table('financial_periods')
    op.drop_index('ux_distribution_category_unallocated_bucket', table_name='distribution_categories', postgresql_where=sa.text('is_unallocated_bucket = true'))
    op.drop_index(op.f('ix_distribution_categories_distribution_rule_id'), table_name='distribution_categories')
    op.drop_table('distribution_categories')
    op.drop_index('ux_savings_dist_rule_user_default', table_name='savings_distribution_rules', postgresql_where=sa.text('is_default = true'))
    op.drop_index(op.f('ix_savings_distribution_rules_user_id'), table_name='savings_distribution_rules')
    op.drop_table('savings_distribution_rules')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index('ux_distribution_rules_user_default', table_name='distribution_rules', postgresql_where=sa.text('is_default = true'))
    op.drop_index(op.f('ix_distribution_rules_user_id'), table_name='distribution_rules')
    op.drop_table('distribution_rules')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_index('ix_bank_account_user_active', table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
